worker_processes 2;
pid /var/run/nginx.pid;
error_log /var/log/nginx.error_log info;

events {
    worker_connections 2000;
}

http {
    include /etc/nginx/mime.types; # sans ça js et css loadent pas 
    default_type application/octet-stream;

    server {
        listen 80;
        server_name localhost;

        root /www/html;
        index index.html;

        location / {
            try_files $uri $uri/ =404;
        }
    }
}
